name: 'build'

on:
  push:
    branches:
      - main
      - 8.x
    tags:
      - '*'
  pull_request:
      branches:
        - main
        - 8.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Setup Elasticsearch
      run: |
        set -e
        docker-compose up -d
        until $(curl --output /dev/null --silent --head --fail -u elastic:changeme http://localhost:9200); do sleep 5; done
        curl -XPOST -u elastic:changeme http://localhost:9200/_license/start_trial?acknowledge=true
    - name: Run build
      run: make build
    - name: Run acceptance tests
      run: ELASTICSEARCH_URLS="http://localhost:9200" ELASTICSEARCH_USERNAME="elastic" ELASTICSEARCH_PASSWORD="changeme" make testacc
    - name: Run acceptance test on license resource
      run: |
        set -e
        cat cover.out > coverage.out
        mv es/resource_elasticsearch_license_test.go.disable es/resource_elasticsearch_license_test.go
        TESTARGS="-run TestAccElasticsearchLicense" ELASTICSEARCH_URLS="http://localhost:9200" ELASTICSEARCH_USERNAME="elastic" ELASTICSEARCH_PASSWORD="changeme" make testacc
        cat cover.out >> coverage.out
    - uses: codecov/codecov-action@v2
      with:
        files: coverage.out
        flags: unittests
        fail_ci_if_error: true
  
  goreleaser:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}